should = require 'should'
parser = require '../src/packrattle/parser'

describe "NoMatch", ->
  it "finds the current line", ->
    text = "line one\nline two\nline 3\n\nline 4"
    state = parser.newState(text)
    x = new parser.NoMatch(state.advance(0), "")
    x.line().should.eql("line one")
    x.lineno.should.equal(0)
    x.xpos.should.equal(0)
    x = new parser.NoMatch(state.advance(5), "")
    x.line().should.eql("line one")
    x.lineno.should.equal(0)
    x.xpos.should.equal(5)
    x = new parser.NoMatch(state.advance(7), "")
    x.line().should.eql("line one")
    x.lineno.should.equal(0)
    x.xpos.should.equal(7)
    x = new parser.NoMatch(state.advance(8), "")
    x.line().should.eql("line one")
    x.lineno.should.equal(0)
    x.xpos.should.equal(8)
    x =new parser.NoMatch(state.advance(9), "")
    x.line().should.eql("line two")
    x.lineno.should.equal(1)
    x.xpos.should.equal(0)
    x = new parser.NoMatch(state.advance(20), "")
    x.line().should.eql("line 3")
    x.lineno.should.equal(2)
    x.xpos.should.equal(2)
    x = new parser.NoMatch(state.advance(25), "")
    x.line().should.eql("")
    x.lineno.should.equal(3)
    x.xpos.should.equal(0)
    x = new parser.NoMatch(state.advance(26), "")
    x.line().should.eql("line 4")
    x.lineno.should.equal(4)
    x.xpos.should.equal(0)
    x = new parser.NoMatch(state.advance(31), "")
    x.line().should.eql("line 4")
    x.lineno.should.equal(4)
    x.xpos.should.equal(5)

